### ISSUE TITLE
There are songs that cannot be found but are on Spotify

### ISSUE THREAD

**Issue by rodriguezrobinj** [WilliamSchack/Spotify-Downloader#12]
![image](https://github.com/user-attachments/assets/1a24edf8-a6b7-445e-b0fb-cef573b171fd)
 There are songs that I try to download but can't find them, but they do exist on Spotify.

**Comment by WilliamSchack** [comment]
So how the program works is that it searches through youtube music for the song then downloads it if it finds the song.

I looked into this song and with this one, it is on youtube but it doesn't get picked up by the program because of this album being the only search result instead of the individual song and it cannot read albums on youtube yet so I will have to go in and have a look into it, change up how I parse the youtube page a bit and see if I can get it to open up the albums and get the result from there.

I am feeling a bit sick at the moment and really cannot be productive even if I wanted to so it will have to wait a few days but as a temporary solution the same song but in the single album (https://open.spotify.com/track/4h9wh7iOZ0GGn8QVp4RAOB?si=b47cf9faa20041bb) downloads fine but this is just putting a bandaid over the issue so hopefully I can get it fixed soon

**Comment by WilliamSchack** [comment]
Just added searching through albums on youtube in the latest commit 45c9d6a

This fixes this song and actually a fair few others not being picked up so thanks for letting me know of this issue :)

The release for this one will be a bit to come out though, I will close this issue when it releases

**Comment by WilliamSchack** [comment]
Released into [v1.5.0](https://github.com/WilliamSchack/Spotify-Downloader/releases/tag/v1.5.0)
