### ISSUE TITLE
Songs Not Found Error

### ISSUE THREAD

**Issue by AndiCee** [WilliamSchack/Spotify-Downloader#16]
Hi William,
After a pretty good run of getting every song this particular playlist [Club Mixes Extended 2](https://open.spotify.com/playlist/55g5F1EkayPzLRM299HcjR?si=0609dc139fc74e14) it has 292 songs and 33 failed.  So I went back into Spotify and tried to download a few one by one and they all had the same error "Songs Not Found". I screen recorded me doing it, plus I screen recorded the list of songs and scrolled through it. 

No rush in replying etc, I just wanted to let you know. :)

https://github.com/user-attachments/assets/1bb50c4d-15d2-46db-a61f-810face54710

https://github.com/user-attachments/assets/f603fe39-c054-4f49-8b3c-989e745c7407

https://github.com/user-attachments/assets/2fd3cc6c-1019-4626-97e9-005530299d89

**Comment by WilliamSchack** [comment]
That is a fair amount of songs that haven't been picked up there so I will definitely have a look at why and see if I can improve the search algorithm because I am always looking for songs that aren't downloading and trying to make as many songs work as possible so thanks for this

I am planning on improving this errors screen soon as well so when I do, I will also add the reason to why they aren't being picked up just so people can know which is a well needed feature now

I am not currently able to work on it but I will have a look in a few days when I am back at my computer, thanks for letting me know of these :)

**Comment by WilliamSchack** [comment]
Just did a quick look on youtube music and it seems it may be the searching not picking them up because the lean on and turn down for what remixes are both on there, but I also saw that the i follow rivers club mix is not on youtube so I would say a fair chunk (I have only looked at those three, just predicting the rest) are able to be downloaded but just need a bit of tweaking to the algorithm

**Comment by AndiCee** [comment]
I think I worked out why the "I Follow Rivers" track doesn't get found, it seems that particular remix is not the original artist.

I just checked again, that song is in the playlist 3 times by 2 different artists, the first 1 is the original artist.

Sorry didn't notice that, so dumb lol
![Spotify Premium 17_08_2024 9_42_42 PM](https://github.com/user-attachments/assets/73a6b1cd-41a5-485f-bbd5-22f9550bc3b5)

**Comment by WilliamSchack** [comment]
So after doing some testing I found that my search query had quotes that youtube did not like so changing that, fixing up the algorithm a bit and with the new album searching I got 24 of the songs downloaded with 7 errors that are all not songs on youtube so they cant be downloaded anyway

I still need to do a bit of testing with other songs to make sure that I didnt mess anything up but the next update should fix this problem and a lot of other songs that are not being detected

I will close this issue when the next release comes out
Thanks for submitting it!

**Comment by WilliamSchack** [comment]
Released into [v1.5.0](https://github.com/WilliamSchack/Spotify-Downloader/releases/tag/v1.5.0)
