### ISSUE TITLE
Instruction at 0x0000...9ECB refrenced memory at 0x0000...2B. the memory could not be read.

### ISSUE THREAD

**Issue by escaper01** [WilliamSchack/Spotify-Downloader#17]
I got this issue
![image](https://github.com/user-attachments/assets/84ee100b-34fa-4ae4-ab72-10accde313ab)
while trying to download
https://open.spotify.com/playlist/37i9dQZF1DZ06evO17QJYk?si=aed2d51764974cce
but the thing is that I configured downloader threads to 6 which could resulted to this issue in the dialog pop up and the glitch in the interface

**Comment by WilliamSchack** [comment]
I thought I fixed this but it always seems to come up again, after doing some testing I have found that it is an issue with the UI and threads not properly being deleted. I thought I fixed that in the last update but I guess not I am trying to fix the issue now I will update you on how it goes

This should hopefully be fixed soon but due to it being a threading issue it may take a bit of time, in the mean time try downloading it with less threads or start the download again without overwriting and it should download

**Comment by WilliamSchack** [comment]
This issue is a lot deeper than I thought it may take a while to fix

**Comment by WilliamSchack** [comment]
Just fixed it, will be released soon

**Comment by escaper01** [comment]
@WilliamSchack 
thanks for the fast patch
