### ISSUE TITLE
Downloaded Musik is not saving

### ISSUE THREAD

**Issue by Tempritscher** [WilliamSchack/Spotify-Downloader#18]
Good Evening
I compiled the latest version with my client_id + secret.
After set a download location and downloading the playlist, the music won't appear on the location.
I also checked: **AppData\Local\Temp\SpotifyDownloader\** for the downlaoded files. The files appear in: **AppData\Local\Temp\SpotifyDownloader\Downloading** for 2 seconds and then gets deleted by the app.
A notification windows shows that no error were found.
The app was tested with and without admin privilege. Result is still the same.

Thats the Playlist i tried to load: https://open.spotify.com/playlist/71o2W183yVTna3HADaOhTp?si=9f0e7670beb741c1

did i miss something or is this a bug?

**Comment by WilliamSchack** [comment]
Sorry about that, its my bad I fixed that issue since the last commit but I forgot to commit it as I was just working on implementing new codecs and kinda forgot about uploading it

I have pushed a new commit with a fix to that as well as a few other things at bc6f3c0

I honestly forgot about people compiling it so I need to be a bit more on top of that and actually update the readme with instructions on it thanks for reminding me :)

**Comment by Tempritscher** [comment]
It doesnt seem to be fixed now.
issue still remain.

**Comment by WilliamSchack** [comment]
Thats odd I have tested it on two machines and it has worked for me

Would you please be able to send your log file and I will have a look at it? (Located at "%temp%/SpotifyDownloader/Log.log")
I wont be able to work on it for a few days since I just went out and do not have access to my computer but I can suggest a fix in the meantime

**Comment by WilliamSchack** [comment]
Oh I just realised, a part of the build also requires the yt-dlp.exe, taglib.dll, and ffmpeg.exe files in the build directory which is not put there automatically (I need to look into this)

Try copying them from the main source directory and put them into the build folder and see if that works

**Comment by Tempritscher** [comment]
This fixed the issue.
thanks man. i love this app

**Comment by WilliamSchack** [comment]
Glad I could help and thanks for using the app its my pleasure :)

I wont close the issue until I have implemented the fix to this also so others in the future don't have to worry about manually transferring the files

**Comment by WilliamSchack** [comment]
Just made it so the files get automatically transferred to the build in 10243de
