### ISSUE TITLE
Audio Distortion

### ISSUE THREAD

**Issue by HELLSNAKES** [WilliamSchack/Spotify-Downloader#19]
It seems like the app will crash if the playlist has more than 50 songs. 
ex : https://open.spotify.com/playlist/37i9dQZF1DZ06evO09G3rH

**Comment by WilliamSchack** [comment]
It look like you closed the issue, did you manage to fix the problem?
Happy to help if you still need

**Comment by HELLSNAKES** [comment]
I have resolved the issue by adding more threads, but it seems there are still quite a few errors, such as the exported audio file being distorted.

**Comment by WilliamSchack** [comment]
That's really strange the audio shouldn't be distorted and if anything I would think more threads would make it worse
The only thing I can think of with distorted audio is that either ytdlp or ffmpeg screwed up in downloading, maybe try 1 thread and see if that fixes the audio issue, my thinking is that the cpu is overloaded with multiple processes on different threads and it messes with it a bit? Not sure honestly

I am out at the minute but I have been working on an update for a while now that I havent released since its not in a good state yet, but I have changed a fair bit since the last one. When I get home in a few hours I will build the project and send the file here then let me know if its fixed but if not then we can keep trying to find the issue

If you wouldnt mind, would you please be able to send the log file here as well located at (%temp%/SpotifyDownloader/Log.log) if the last time you used the application it had this issue? I can look through it and see if anything went wrong during the download to hopefully find the issue

**Comment by HELLSNAKES** [comment]
I tried a lower threads, around under 20, but the audio still seems distorted.  

[Log.log](https://github.com/user-attachments/files/17405751/Log.log)

[Log2.log](https://github.com/user-attachments/files/17405762/Log2.log)

**Comment by WilliamSchack** [comment]
Just looking into the log it looks like you are using 50 threads to download the songs, this is probably the issue as there will be 50 processes of ytdlp and ffmpeg trying to fight for resources simultaneously and that will most likely cause an issue. Try downloading with 6 or less threads and see if that works fine

In regards to kmplayer after a quick search it just seems like another media player so im not sure why its working with that and not others, what audio player are you using when the audio is distorted?

**Comment by HELLSNAKES** [comment]
I tried a lower threads, around under 10,but the audio still seems distorted.

I hear the distortion when using the default player on my iPhone or some audio devices like music players, or when sending it through Discord.

**Comment by WilliamSchack** [comment]
Someone else just let me know at the perfect time in issue #20, it turns out i have my default normalise audio set positive instead of negative...

Thats your issue

Go into the settings and change it to -14db instead of 14db and it should work

I cannot believe i let this one through thats my bad

**Comment by HELLSNAKES** [comment]
I changed the normalize back to -14db and it worked fine again.   
Thanks for this awesome app!
