### ISSUE TITLE
does it download all songs from given artist

### ISSUE THREAD

**Issue by francqz31** [WilliamSchack/Spotify-Downloader#2]
Hey amazing project just what I was looking for , i got 2 questions 
1-does it download all songs from given artist , or even full albums , or just song by song
2-does it download directly from spotify ? or does it search the id of the song and download from youtube music ? and what is the highest quality that this tool download?

Thanks in advance

**Comment by WilliamSchack** [comment]
Hello and thanks for using my program!

For the first question, it cannot download all songs from a given artist but it can download albums, and individual songs. I might have a look into downloading songs from an artist but for now if you really want you could try to compile all of their songs into a playlist and download that but otherwise i don't have any other suggestions sorry. If you need any help inputting the songs into the program there is a guide [here](https://github.com/WilliamSchack/Spotify-Downloader?tab=readme-ov-file#usage) under Setup > How To Find Your URL

For the second question, it does not download the songs directly from spotify but it uses the album, title and artist to search for the song on youtube music and sort through the results to make sure that it is correct. I have tested roughly 500 songs from varying artist and genres and it has only gotten about 5-10 wrong which were songs that were not on youtube but had popular covers which it downloaded so it is pretty accurate and should download all the songs that are on youtube.

For the quality of the music, it gets the highest quality stream from youtube and downloads that which for all of my cases has a bitrate of 124kpbs which sounds exactly the same as it does on spotify to me at least

If you have any more questions feel free to leave another comment here if you like but if not I will close the issue in roughly 24 hours 

Next commit I will update the readme with a FAQ and put some general questions and answers there so hopefully it helps you and others in the future

Thanks again for the questions and hope you enjoy the program and updates to come! :)

**Comment by WilliamSchack** [comment]
No problem! :)
I have never heard of deezer before and will have a look into it but I probably wont change the program up too much to download from them but its definitely on the table. I might have a look into increasing the audio quality in the future as well but for now it's good enough for general use. Good luck finding your audio!

**Comment by WilliamSchack** [comment]
So it turns out that when I normalized the audio I was compressing it down to 124kb/s which I have fixed in the [latest update.](https://github.com/WilliamSchack/Spotify-Downloader/releases/tag/v1.2.0) You can now download from 33-256kb/s which is configurable in the settings. In this case, converting the audio to any higher than 256kb/s would be a waste as the audio will just be filled with empty space but this is much better than before.

I know for your case personally it is still not enough but this made me have a look into it and I would not have found this out without it so I cannot thank you enough!

**Comment by WilliamSchack** [comment]
Glad that you found a solution and in terms of their speed im not too sure exactly it could be some sort of rate limiting prevention with the api they are using or a limitation with the way they download from deezer but im not too sure since I havent looked into it. That downloader does seem pretty fleshed out though so the downloading speed is probably nothing new, maybe have a look theough the issues see if anyone else has had the same problem?

Good to hear that its all going well and I wish you safe and speedy high quality downloading
