### ISSUE TITLE
Not able to download playlists anymore

### ISSUE THREAD

**Issue by amvvi** [WilliamSchack/Spotify-Downloader#24]
I got the app. Love the interface and all but it wont download. It keeps saying files not found. Kindly update.

**Comment by WilliamSchack** [comment]
Hopefully I can fix this with you

So what exactly is the error message? If it takes you to the "Songs Not Found" screen then those songs cannot be found on youtube as the program searches for the songs and downloads them from there, if this is the issue then there isn't really much I can do about that sorry because of how the app is set up

If that isn't the issue would you please be able to let me know what the error message is that pops up and send the log located at (%temp%/SpotifyDownloader/Log.log) so that I can see exactly what it is and help you easier

Sorry for the inconvenience hopefully we can get this sorted out

**Comment by amvvi** [comment]
Hi. So it happens with whatever playlist I input in the URL. It basically
does a search then responds "Song Not Found".

I attached a screen shot. Am trying to find the log so that you can see the
process.[image: Screenshot 2024-11-06 103346.png]

**Comment by amvvi** [comment]
![Screenshot 2024-11-06 103346](https://github.com/user-attachments/assets/bff139fa-be72-464b-aa45-ef5e4f869617)


That's the screen am getting.

**Comment by WilliamSchack** [comment]
So I just tried downloading those three songs that showed an error and they worked fine on my end, would you please be able to send the log here so I can see what is going wrong its located at (%temp%/SpotifyDownloader/Log.log) just chuck it into your file explorer or win+r and it should open

Honestly have no clue what it could be maybe an internet error that doesn't like searching youtube but I doubt it

**Comment by amvvi** [comment]
Here is the log file.

**Comment by amvvi** [comment]
[Log.log](https://github.com/user-attachments/files/17647449/Log.log)

**Comment by WilliamSchack** [comment]
Sorry about the wait I went to bed just before the last message you sent and was busy earlier today

So I have tested your playlist with the same settings on my machine and oddly they all download with no errors at all on both the public release and the one I am working on which is strange. The logs also show no apparent errors that would mess with the downloads or the searching so this one might be a bit hard to figure out

I have uploaded the release I am currently working on to google drive at (https://drive.google.com/file/d/1G3eMHJsgCcBDeyWUQwnB4CCZWzrmrqKl/view?usp=sharing) with a bunch of extra logging things added specifically to look into the whole search process so we can see exactly where it failed (I also found an issue with the folder sorting files not working properly when testing with your settings so that fixed in this build also)

Would you please be able to download this release and see if it works? Maybe I have done something in between that fixed your issue but I doubt that. If it inevitably doesnt work could you please send the new log at the location?

Sorry for the inconvenience but there isn't really much I can do with the current build, the modified one will help narrow this down a lot easier

**Comment by amvvi** [comment]
Thanks for the release. Am hoping this isn't a regional block by YouTube
for the music. However thanks for the quick response. Let me test the
release now.

Will share feedback

**Comment by WilliamSchack** [comment]
Actually didn't consider regional blocks at all, just found a website to check those at (https://watannetwork.com/tools/blocked/#url=Zoe2DdyLyrk, not sure if its good or not just first google search) for one of the issue songs called Daily by Ryan Ofei check that to see if you are region locked

If possible as well maybe try a vpn to another region and see if that works because that should bypass any region lock

**Comment by amvvi** [comment]
Hey thanks for the help. The VPN advice worked. Turns out youtube geoblocks
the app so when a VPN runs downloads are working except for the obvious
blow to the process speed. Otherwise app is working fine now.

**Comment by WilliamSchack** [comment]
Alright glad I could help just a bummer about the location blocking but glad we found a solution :)
