### ISSUE TITLE
The songs are not saved in the location folder I choose

### ISSUE THREAD

**Issue by rodriguezrobinj** [WilliamSchack/Spotify-Downloader#3]
The songs are not saved in the location folder that I choose, but I have to search for them through Appdata/Local/Temp/SpotifyDownloader

**Comment by WilliamSchack** [comment]
Glad you found a solution but I am curious, what was the issue and how did you fix it? I would love to add some sort of warning pop up to remove confusion for people using the program in the future

Thanks for using my program as well :)

**Comment by rodriguezrobinj** [comment]
The program does its job very well, I appreciate that, the problem is that instead of saving the songs downloads in the location I choose.

![image](https://github.com/WilliamSchack/Spotify-Downloader/assets/108781192/aeaef85d-eac7-4a59-9ab1-8815e5b0f407)

It saves them in **Appdata/Local/Temp/SpotifyDownloader**, which makes it tedious for when I want to see the songs to download and they do not appear in the folder I chose as destination. Instead it sends them to a folder that people can hardly believe they are in, which in this case is the folder where all the junk is stored. The **Temp** folder

**Comment by WilliamSchack** [comment]
Oh my bad i though that you resolved the issue since it was closed but i am happy to help with it

So the program stores its files in the temp folder before moving it to the target location later but that clearly has not worked properly here

Does your music folder require admin permissions, or in this case are you on the “user” account? I have not implemented a way to download to those yet and honestly should have implemented some sort of warning.

Does the downloading work on the previous version? This may be an issue that has arose in the latest update that is not on my machine

If those dont work would you please be able to try downloading to a file at the root of your drive (eg C:/songs) just to see if it is a writing permissions thing or whether I need to do some more digging

I will do some testing with it to try and figure this out but it does seem strange since the music folder is where I downloaded my songs to in testing as well. I will try my best to help you out here and hopefully we can fix your issue!

**Comment by WilliamSchack** [comment]
So I have implemented a way to detect errors in a folder to check if you can download to it or not. Now it will tell you the error if a directory cannot be used to download, and it will give you the option to run as admin to resolve most issues with that.

If you are still having the issue would you please be able to try the (new version)[https://github.com/WilliamSchack/Spotify-Downloader/releases/tag/v1.2.1] and follow the prompt to run as administrator?

If it still does not work what is the error shown in the dialogue box? If it is something different to what I have seen it will help me to do some more testing to find out the issue

Hopefully this update fixes your problem and if not it should clear up some confusion for others in the future, thank you!

**Comment by rodriguezrobinj** [comment]
That's it, the problem was solved, although I simply ran it like the previous version, I ran the program normally, I put the link of the song, and what it did was download the song temporarily in the location Appdata/Local/Temp/SpotifyDownloader and then it deleted it, but it did not save it in the folder that it had selected, but now with this new version it now saves it in the location where it wanted in the previous version which did not save it.

**Comment by WilliamSchack** [comment]
Glad I could help!
