### ISSUE TITLE
Feature Request: Have the app still remain open after you have downloaded the song or playlist

### ISSUE THREAD

**Issue by rodriguezrobinj** [WilliamSchack/Spotify-Downloader#4]
When the song download is in process.

 ![image](https://github.com/WilliamSchack/Spotify-Downloader/assets/108781192/86dce625-0e28-435e-9bc8-cbef3293b1e5)

 And it is completed.

 ![image](https://github.com/WilliamSchack/Spotify-Downloader/assets/108781192/2c764d1b-8e6c-4397-a112-76c0489dc95d)

 It closes after completing its function, which makes it annoying when I want to download several songs individually, so I have to open the program every time I download a song.

**Comment by WilliamSchack** [comment]
Going to be completely honest I set this up when I first created the program and completely forgot that I planned to do this... whoops...
Thanks for reminding me I'll implement it tonight and let you know when its updated!
Thanks for using the program as well!

**Comment by WilliamSchack** [comment]
Just implemented this feature ([here](https://github.com/WilliamSchack/Spotify-Downloader/commit/aa7467e9ea77ad1f6f92a69c1882e82fe42c5d8d)) and it will be released along side the next update :)

It took a bit longer to setup than I initially thought as the multithreading made it a bit of a pain but in testing it was much more convenient to have it reset to the setup screen rather than me restarting the program so thanks for the request!

**Comment by WilliamSchack** [comment]
This is now released into [v1.3.0](https://github.com/WilliamSchack/Spotify-Downloader/releases/tag/v1.3.0) :)
